import type {
  AnnualPlanResult,
  BestVacationPeriod,
  CalendarExportBundle,
  CalendarExportEvent,
} from "@/lib/domain/types";
import type { AppLanguage } from "@/lib/i18n";

export function buildPeriodCalendarBundle({
  period,
  language,
  year,
}: {
  period: BestVacationPeriod;
  language: AppLanguage;
  year: number;
}): CalendarExportBundle {
  return {
    filename: `ponts-malins-${year}-${period.startDate.toISOString().slice(0, 10)}.ics`,
    events: [
      {
        title:
          language === "en"
            ? `Ponts Malins - ${period.totalDaysOff} days off`
            : `Ponts Malins - ${period.totalDaysOff} jours de repos`,
        startDate: period.startDate,
        endDate: period.endDate,
        description: buildPeriodDescription(period, language),
      },
    ],
  };
}

export function buildAnnualPlanCalendarBundle({
  plan,
  language,
  year,
}: {
  plan: AnnualPlanResult;
  language: AppLanguage;
  year: number;
}): CalendarExportBundle {
  return {
    filename: `ponts-malins-plan-annuel-${year}.ics`,
    events: plan.segments.map((segment, index) => ({
      title:
        language === "en"
          ? `Ponts Malins - Annual plan ${index + 1}`
          : `Ponts Malins - Plan annuel ${index + 1}`,
      startDate: segment.period.startDate,
      endDate: segment.period.endDate,
      description: buildPeriodDescription(segment.period, language),
    })),
  };
}

export function buildIcsContent(bundle: CalendarExportBundle): string {
  const lines = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Ponts Malins//FR",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
  ];

  for (const event of bundle.events) {
    lines.push(
      "BEGIN:VEVENT",
      `UID:${createUid(event)}`,
      `DTSTAMP:${formatDateTimeUtc(new Date())}`,
      `DTSTART;VALUE=DATE:${formatDate(event.startDate)}`,
      `DTEND;VALUE=DATE:${formatDate(addDays(event.endDate, 1))}`,
      `SUMMARY:${escapeIcsText(event.title)}`,
      `DESCRIPTION:${escapeIcsText(event.description)}`,
      "END:VEVENT",
    );
  }

  lines.push("END:VCALENDAR");
  return lines.join("\r\n");
}

export function downloadCalendarBundle(bundle: CalendarExportBundle) {
  const blob = new Blob([buildIcsContent(bundle)], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = bundle.filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function buildGoogleCalendarUrl(event: CalendarExportEvent): string {
  const params = new URLSearchParams({
    action: "TEMPLATE",
    text: event.title,
    dates: `${formatDate(event.startDate)}/${formatDate(addDays(event.endDate, 1))}`,
    details: event.description,
  });

  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

function buildPeriodDescription(period: BestVacationPeriod, language: AppLanguage): string {
  const holidayNames = period.includedHolidays.map((holiday) => holiday.localName).join(", ");
  return language === "en"
    ? [
        `${period.totalDaysOff} days off.`,
        `${period.paidLeaveDaysUsed} paid leave day(s), ${period.rttDaysUsed} RTT.`,
        holidayNames ? `Public holidays included: ${holidayNames}.` : "",
        "Generated by Ponts Malins.",
      ]
        .filter(Boolean)
        .join(" ")
    : [
        `${period.totalDaysOff} jours de repos.`,
        `${period.paidLeaveDaysUsed} jour(s) de congé payé, ${period.rttDaysUsed} RTT.`,
        holidayNames ? `Jours fériés inclus : ${holidayNames}.` : "",
        "Généré par Ponts Malins.",
      ]
        .filter(Boolean)
        .join(" ");
}

function createUid(event: CalendarExportEvent) {
  return `${event.startDate.getTime()}-${event.endDate.getTime()}@pontsmalins.com`;
}

function formatDate(date: Date) {
  return date.toISOString().slice(0, 10).replace(/-/g, "");
}

function formatDateTimeUtc(date: Date) {
  return date
    .toISOString()
    .replace(/[-:]/g, "")
    .replace(/\.\d{3}Z$/, "Z");
}

function escapeIcsText(value: string) {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/\n/g, "\\n")
    .replace(/,/g, "\\,")
    .replace(/;/g, "\\;");
}

function addDays(date: Date, days: number) {
  const next = new Date(date);
  next.setDate(next.getDate() + days);
  return next;
}
